--Total revenue generated from each city
SELECT A.CITY,
	SUM(TOTALTRANSACTIONREVENUE) AS REVENUE_GENERATED
FROM ALLSESSIONS AS A
WHERE CITY IS NOT NULL
	AND TOTALTRANSACTIONREVENUE IS NOT NULL
GROUP BY A.CITY
ORDER BY SUM(TOTALTRANSACTIONREVENUE) DESC 

--Total revenue generated from each country
SELECT A.COUNTRY,
	SUM(TOTALTRANSACTIONREVENUE) AS REVENUE_GENERATED
FROM ALLSESSIONS AS A
WHERE COUNTRY IS NOT NULL
	AND TOTALTRANSACTIONREVENUE IS NOT NULL
GROUP BY A.COUNTRY
ORDER BY SUM(TOTALTRANSACTIONREVENUE) DESC 